src/SQLite.cs
Virtual tables (tables implementing full-text search i.e. FTS3/FTS4)
can be created using CreateTable() by specifying
CreateFlags.FullTextSearch3 or CreateFlags.FullTextSearch4.
=> Facilitates creation of virtual tables.

sqlite-net-pcl.nuspec
Update sqlite-net-pcl.nuspec with the new package ID for SQLitePCLRaw.bundle_green.
I have not built and test sqlite-net-pcl with this change.
=> update to SQLitePCLRaw 1.0

src/SQLite.cs
I added an attribute to store and read custom Enums as varchar.
Just add it like this
```csharp
[StoreAsText]
public enum CustomEnum
{
A,
B,
C
}
```
=> Store Enum as text using StoreAsTextAttribute

src/SQLite.cs, tests/DateTimeTest.cs
this fix allow the sqlite file to be consumed across different culture info devices
=> More precise and invariant culture datetime store format

src/SQLite.cs, tests/EnumCacheTest.cs, tests/EnumTest.cs, tests/SQLite.Tests.csproj, tests/packages.config
Still WIP.
For now:
- Added NuGet reference to NUnit 2.6.4
- Added unit tests for enum values
=> Enum performance improvements to solve #458

src/SQLiteAsync.cs
Added support to SQLiteAsync for ThenBy ThenByDescending
=> -SQLiteAsync added support for ThenBy ThenByDescending

src/SQLiteAsync.cs
DeleteAllAsync
InsertOrReplaceAsync
=> Added two new methods to SqliteAsyncConnection

Makefile, SQLite.sln, nuget/SQLite-net-base/SQLite-net-base.csproj, nuget/SQLite-net-std/SQLite-net-std.csproj, nuget/SQLite-net/SQLite-net.csproj, nuget/SQLite-net/packages.config, sqlite-net-base.nuspec, sqlite-net-pcl.nuspec, sqlite-net.nuspec, src/SQLite.cs
The idea is that you can use this version and pick your Raw provider.
This is for #568
=> SQLite-net Base that references only SQLitePCLRaw.core

src/SQLite.cs, src/SQLiteAsync.cs
This may work for writing too, but not tested.
=> Now when in full mutex mode (serialized), reading can happen  without locking. 

.gitignore
As now a lot of stuff is created by Visual Studio, CodeRush, etc.
=> Updated .gitignore to modern set

nuget/SQLite-net-base/SQLite-net-base.csproj, nuget/SQLite-net-sqlcipher/SQLite-net-sqlcipher.csproj, nuget/SQLite-net-std/SQLite-net-std.csproj, nuget/SQLite-net/SQLite-net.csproj, nuget/SQLite-net/packages.config, src/SQLite.cs
Support for VFS
https://www.sqlite.org/vfs.html
=> Support for VFS

.github/workflows/build.yml
=> GitHub Build Script

src/SQLite.cs
We were looking to get more detailed messages for our constraints. It looks like they are in the error message. 
This should resolve #126, #728, #829
=> Fix getting detailed error messages

src/SQLite.cs, src/SQLiteAsync.cs
This is just a quick PR for the spelling of Jounral/Journal in the comments
Wouldn't believe how many times I double checked my own spelling here.
=> Spelling update on Journal

src/SQLite.cs
Fix comment of SQLiteConnection.Trace
=> Minor comment fix

Directory.Build.props, nuget/SQLite-net-base/SQLite-net-base.csproj, nuget/SQLite-net-sqlcipher/SQLite-net-sqlcipher.csproj, nuget/SQLite-net-std/SQLite-net-std.csproj
Please consider updating SQLitePCLRaw from 2.0.3 to 2.0.4
=> Update SQLitePCLRaw from 2.0.3 to 2.0.4

tests/DateTimeTest.cs
Fixes #950 
Simple fix for the two tests... they weren't expecting what the library actually does.
=> fixed tests for issue #950

src/SQLite.cs
fix #1060
*fix unknown variable name in preprocessor statement
=> Fix for issue #1060 - Unknown variable in preprocessor statement

README.md, src/SQLite.cs, src/SQLiteAsync.cs
Added ISQLiteConnection and ISQLiteAsyncConnection interfaces. Updated readme to reference sqlite-net-base nuget package and SQLiteAsync source file.  Disabled CS1591 XML Doc Comments warning for SQLiteAsync.cs.
=> Added ISQLiteConnection and ISQLiteAsyncConnection interfaces

README.md
Some people may need to ignore a field. It's a little hard to find this method, such as me, so I marked it here.
=> Update README.md, specifies how to ignore a field.

src/SQLite.cs
Update IndexedAttribute to allow multiple indexes on a column (based off issue #122)
=> Update IndexedAttribute to allow multiple indexes on a column

src/SQLite.cs, tests/SQLite.Tests/SQLCipherTest.cs
Added SetReKey to change the password of sqlcipher db.
https://www.zetetic.net/sqlcipher/sqlcipher-api/
=> Add SetReKey for SQLCipher

src/SQLite.cs
Fixes https://github.com/praeclarum/sqlite-net/issues/1198
=> Support SQLITE_OPEN_URI & SQLITE_OPEN_MEMORY flags

src/SQLite.cs, src/SQLiteAsync.cs
Was exploring how this works, but my IDE (Rider) was showing project errors due to missing XML closing tags. 
Have added the missing ones if you care to include it.
=> Add missing XML doc closing tags
