praeclarum/sqlite-net

README.mdown

Running this code would throw a NullReferenceException

Correct ExecuteScalarAsync call in documentation

---

src/SQLite.cs
tests/LinqTest.cs

Just added a case for `ExpressionType.Not` in `CompileExpr`

Fixed issue #303: added support for NOT

---

src/SQLite.cs
tests/DeleteTest.cs
tests/SQLite.Tests.csproj

Added a Delete function which allows records to be deleted using a predicate.
See StackOverflow question for details:
http://stackoverflow.com/questions/21123170/is-there-a-way-to-delete-in-sqlite-net-by-using-a-predicate/22055268#22055268
Can delete using:
conn.Table<MyEntity>().Delete(t => t.someProperty == someValue);

Add ability to Delete records using a predicate.

---

src/SQLite.cs

SQLite doesn't distinguish between int types,
it gladly stores between 1 and 64 bits of data
in an integer column without much fuss.
https://www.sqlite.org/datatype3.html
However, when setting an auto-incrementing PK,
the column must be explicitly typed as "integer"
within the SQL itself.
This fix passes the test suite on Win32/sqlite.dll
and when using CSharp-SQLite when specifying
USE_CSHARP_SQLITE as a build argument.

Treat uint32 and int64 as SQLite integers

---

src/SQLiteAsync.cs

Hi Frank,
I would like to support deleting my database file and creating it again, but the connection pooling is causing sqlite-net to keep a reference to the deleted file, which is leading to read only errors later on.
It seems I need to use the SQLiteConnectionPool.Shared.Reset() method after I Delete the file, but the SQLiteConnectionPool class has been made internal in the sqlite-net implementation, preventing use.
I have been unable to find any other way to clear the connection pool that references the old DB file.
I noticed the following patch was submitted, but there were concerns with the implementation there:
https://github.com/praeclarum/sqlite-net/pull/320
I am hoping that my pull request may be easier to accept, as it contains far less significant changes.
Thanks,
Ryan

Implement SQLiteAsyncConnection.ResetPool()

---

src/SQLiteAsync.cs

CreateTablesAsync<T,T2,T3> and CreateTablesAsync<T,T2,T3,T4> did not create a table for type T.

Bug fix. CreateTablesAsync() did not create a table for the first type parameter.

---

src/SQLite.cs
tests/SQLite.Tests.csproj
tests/StringQueryTest.cs

Fix for issue #121 
The C# compiler turns `x => x == "Foo"` into a simple expression tree
```cs
Equals(Parameter "x", Constant "Foo")`
```
But the VB compiler turns `Function(x) x = "Foo"` into a call to a helper method as below. It passes either `true` or `false` to the helper method depending on whether the user wrote `Option Compare Binary` (case-sensitive) or `Option Compare Text` (case insensitive).
```cs
Equals(Call[CompareString](Parameter "x", Constant "Foo", true/false), Constant 0)
```
That's why SQLite gives an error message "method CompareString not recognized".
The solution is explained by formed VB compiler team lead Timothy Ng:
http://blogs.msdn.com/b/vbteam/archive/2007/09/18/vb-expression-trees-string-comparisons.aspx
He writes, "if your provider doesn't care about string …

Allow expression-tree-compiler to read VB string comparisons

---

src/SQLite.cs

Acknownledges the `disposing` flag passed either by the `Dispose` or the `~SQLiteConnection` finalizer.
Prevents throwing exceptions on the finalizer thread.
Prevents calling dispose on the _mappings' sqlInsertCommand when called via finalizer

Levarages sqlite_close_2 on the finalizer.

---

sqlite-net-pcl.nuspec
src/SQLite.cs

SQLitePCL.bundle_green is a batteries-included package which brings in SQLitePCL.raw and the necessary deps for SQLite-net users.

switch to SQLitePCL.bundle_green

---

src/SQLite.cs

It's entirely too easy to accidentally use the extension methods that
already exist, but they generate horrible queries that potentially
build enormous in-memory lists just to grab one element.

Add versions of TableQuery.First* that take predicate

---

src/SQLite.cs

On other platforms I have been able to use sqlite as an in-memory database, which is very handy for integration testing.
With sqlite-net this is not possible out-of-the-box on the  NETFX_CORE-platform, as it is hard-wired to Windows.Storage.ApplicationData.Current.LocalFolder.Path.
This pull request enables the in-memory capability by creating a connection like this: 
`var connection = new SQLiteAsyncConnection(":memory:");`
(based on [https://www.sqlite.org/inmemorydb.html](https://www.sqlite.org/inmemorydb.html))
Best regards
Tommy Wendelborg

In-memory capability for NETFX_CORE

---

src/SQLite.cs

The FindColumn used by the ExecuteDeferredQuery will now compare the columns in lower case, because if the Property or MappedColumnName is different of the Table column name, the value of that column will be null.

Comparing the column name in LowerCase.

---

nuget/SQLite-net/SQLite-net.csproj
nuget/SQLite-net/packages.config
sqlite-net-pcl.nuspec
src/SQLite.cs

Not an urgent PR, but:
SQLitePCL.Batteries_V2.Init() gives us a bit more flexibility in dealing with cases where somebody wants to use a different bundle.
A little more detail:
Currently if somebody wants to use sqlite-net-pcl with SQLCipher, or if they don't want to use the system SQLite on iOS, there is no good way to help them.
Batteries_V2.Init() makes it possible to bait-and-switch one bundle for another, if it's done carefully.  Reference sqlite-net-pcl only from the PCL project.  In the app project, do not reference sqlite-net-pcl, but _do_ reference the bundle you want instead of bundle_green.

chg SQLitePCL.Batteries.Init() to SQLitePCL.Batteries_V2.Init(), which requires SQLitePCL.raw 1.1.0

---

tests/ConcurrencyTest.cs
tests/SQLite.Tests.csproj
tests/SQLite.Tests.iOS/SQLite.Tests.iOS.csproj

Hi, 
I had some multithreaded concurrency issues on iOS. I wrote and added this unittest to reproduce the issues. The unittest only fails on iOS, not on UWP, Android and MacOS.
It seems that SQLite on iOS should be thread safe (it's compiled threadsafe, I checked sqlite3_threadsafe). However if you are using SQLite multithreaded with Read and ReadWrite connections this fails. Only using ReadWrite connection then there is not problem.
Any ideas on this ?
Regards,
Jeroen

Concurrency Test to prove failure on iOS

---

src/SQLite.cs
tests/EnumCacheTest.cs

I created a test to expose the InvalidCastException issue ( #531 ) and created a patch. However I have not investigated the performance implications.

Boxing required in EnumCacheInfo to avoid invalid cast exception

---

src/SQLite.cs

for issue #488 
ColumnBlob returns null, but in this case we want to return an empty byte[]

fix for bundle_green ByteArray Empty vs null test

---

src/SQLite.cs

Use IsDefined to check for IgnoreAttribute

---

src/SQLite.cs
tests/EnumNullableTest.cs
tests/SQLite.Tests.csproj

When a property is typed nullable enum, Query won't work.
The fix is in Column.SetValue. It's managing a special case for enum.
The commit adds :
-    add nullable enum test case
-    fix SetValue when enum
ps : sorry when rollbacking with git to previous commit to remove windows characters, it ended up closing the other pull request... Thanks for the reminder!

Fix for Nullable Enum

---

src/SQLite.cs
tests/StringQueryTest.cs

StartsWith, EndsWith, and Contains generated SQL behaves like the System.String methods used to construct the query:
Contains is case sensitive, using instr() instead of like(). ToUpper() or ToLower can be used to compare without case sensitivity.
StartsWith and EndsWith are case sensitive unless a case insensitive StringComparison argument is passed using substr() = ? or the original like() depending upon case sensitivity

Case sensitivity in System.String methods used in LINQ queries

---

Makefile
SQLite.sln
nuget/SQLite-net-std/SQLite-net-std.csproj
nuget/SQLite-net/SQLite-net.csproj
sqlite-net-pcl.nuspec
sqlite-net.nuspec
src/AssemblyInfo.cs

This patch:
1. Adds a .NET Standard 1.1 project to the repo that uses the new build system
2. Uses target-specific dependencies in the unspec to improve packaging
Thanks to @jamesmontemagno for PR #546 on which this was based

Improve .NET Standard nuget

---

src/SQLiteAsync.cs

according to this article : https://blogs.msdn.microsoft.com/pfxteam/2011/10/24/task-run-vs-task-factory-startnew/
add default Task.Factory.StartNew parameter to do the same with Task.Run

use default parameter to Task.Factory.StartNew to do the same as Task.Run

---

src/SQLite.cs

allow queries like
var nullableInt = default(int?);
connection
.Table<Test>()
.Where(x => x.Int < nullableInt);
which is equivalent to
connection
.Query<Test>("SELECT * FROM [Test] WHERE [Int] < ?", nullableInt);

allow comparison with nullable parameter

---

src/SQLite.cs
tests/ScalarTest.cs

When using ExecuteScalar<T>() with value types, no NULL values can be determined. Extension of  ExecuteScalar<T>()/ReadCol() to support System.Nullable<T>.

ExecuteScalar<T>() with System.Nullable<T> support

---

src/SQLite.cs
tests/ConcurrencyTest.cs

This addresses a race condition where a new PreparedSqliteInsertCommand object was returned in a disposed state if a second object was created and inserted into the command map during its creation. The fix always returns the item inserted into the command map.
This supposedly fixes the hard to reproduce #761 and potentially #530 .

Fix to #761, preventing returning a disposed command object

---

src/SQLite.cs
src/SQLiteAsync.cs
tests/DateTimeTest.cs
tests/SQLite.Tests.csproj
tests/TestDb.cs
tests/TimeSpanTest.cs

We're working with databases that are consumed by tools written in languages other than C#.  It's quite a hassle to convert between the C# native ticks format and a more portable one (or worse, mixing the formats in the same DB). This patch lets us specify the format string for `DateTime`s, as well as an option to use strings for `TimeSpan`s.  `DateTimeOffset`s are unchanged.

Custom datetime format, string-based timespan

---

src/SQLite.cs

To properly do prepared statements
Overload `CreateCommand(string cmdText, Dictionary<string, object> args)`

Issues: The right way to do prepared statements

---

src/SQLite.cs

Seems like "extra" was forgotten in the non-transactional path and only passed along when running in a transaction

Pass along "extra" correctly on InsertAll

---

tests/ReadmeTest.cs

I personally use "NCrunch" as nunit test runner. among the other things it supports parallel execution of tests (which should work because tests are supposed to be able to run in total isolation among each other) and a "churn mode" which actually runs tests continuosly, totally non-stop, until they break.
The tests in this source file:
1.  couldn't be run in parallel because they were trying to delete and reuse the same file. When run in parallel they were breaking because they were trying to delete a database file being used by another test.
2. couldn't be run continuosly because they weren't doing any proper database.close() operation, so if the garbage collector hasn't been run yet, the file resulted still in use and couldn't be deleted (this doesn't apply obviously to the test using a …

ReadmeTest.cs were failing if run in parallel execution or continuosly

---

tests/AsyncTests.cs

Also here, considering how essential is the "run continuosly until it fails" feature of NCrunch for discovering concurrency issues, I refactored the tests in order to be run independently and concurrently. it is even possible to spawn multiple  concurrent instances of the same test on different threads of the same process (again... NCrunch does it).
You see a lot of changes because I had to add a level of indentation to each test, but actually what I did is pretty simple:
1. I removed the "SetUp" method that initialized the instance-level database connection, I removed also such connection too. 
2. i introduced a dedicated TestEnvironment disposable class that encapsulates a new database instance for each test, exposing also the database file path and its connect string.
3. this class, in …

Now AsyncTests can be run in parallel without interfering each other.

---

src/SQLite.cs

This PR changes the way that we do column lookups to be once-per-query rather than once-per row.  By doing this, we can speed up large query retrieval by ~500%.  
We have to do some funky stuff re: creating dynamic strongly-typed setter delegates, but other libraries have already gone this way (such as Protobuf), so we can follow in their footsteps a bit.
SQLite.net is very easy to use, and has great facility for mapping from SQLite tables into object properties.  However, for very large queries, response times can be a bit on the slow side:
// *** Method 1 ***
var orders = conn.Query<OrderDetail>("select * from [OrderDetail]");
If OrderDetail is 1 million records or so, then performance is very poor:
```Retrieved 1000000 records in 14852 ms```
Why does it take 15 seconds to query from a …

Performance Optimization: Fast Column Setters

---

src/SQLite.cs

The SQLitePCL.raw 2.0.5 prerelease (ericsink/SQLitePCL.raw#392) has been updated by @ericsink to include SQLCipher version 4.4.2. As of SQLCipher 4.3.0 the `PRAGMA key` command now returns a scalar value result, `ok`. This change was made to maintain consistency with upstream SQLite. 
As a result, sqlite-net should be updated to call `PRAGMA key` using `ExecuteScalar<string>`. The use of `Execute` on master and in the current 1.7.335 will resulting in a `SQLiteException: not an error` exception. 
This issue is also being tracked under ericsink/SQLitePCL.raw#394.

use ExecuteScalar<string> to handle 'ok' result from PRAGMA key

---

src/SQLite.cs
tests/SQLite.Tests/DbCommandTest.cs
tests/SQLite.Tests/SQLite.Tests.csproj

Fixes https://github.com/praeclarum/sqlite-net/issues/1048

Fix for issue "1.8.0-beta - System.ArgumentException: method arguments are incompatible" and Unit Tests

---

Directory.Build.props

Fix according to https://github.com/NuGet/Home/wiki/Packaging-Icon-within-the-nupkg

Fix PackageIcon

---

src/SQLite.cs

I know that SQLite3 does not support [unsigned 64-bit integers for columns](https://www.sqlite.org/c3ref/column_blob.html)
but seeing the way `byte` / `sbyte` are supported in this library, I think other integral types should be supported as well.
Resolves #998

Add support for ulong

---

.gitignore
src/SQLite.cs

It's a minor fix, but if ISqliteConnection is not declared as a IDisposable interface, It can't be used with the "using" c# pattern.
I mean, this code, before this modification would not compile:
```csharp
using (ISQLiteConnection conn = MyConnectionFactory.GetConnection())
{
..... // use conn
}
```
I also added to .gitignore the project configuration files created by ncrunch (see https://www.ncrunch.net/)

ISqliteConnection should be derived from IDisposable
